### ISSUE TITLE
Update teritori, Change amount ticker utori, not muon in create validator

### ISSUE THREAD

**Issue by vanzzdark** [StakeTake/guidecosmos#100]
Should be like this

"Create Validator")
teritorid tx staking create-validator \
  --amount 1000000utori \
  --from $WALLETNAME \
  --commission-max-change-rate "0.05" \
  --commission-max-rate "0.20" \
  --commission-rate "0.05" \
  --min-self-delegation "1" \
  --pubkey $(teritorid tendermint show-validator) \
  --moniker $NODENAME \
  --chain-id $CHAIN_ID \
  --gas 300000 \
  -y

**Comment by vanzzdark** [comment]
Should be like this

"Create Validator")
teritorid tx staking create-validator \
  --amount 1000000utori \
  --from $WALLETNAME \
  --commission-max-change-rate "0.05" \
  --commission-max-rate "0.20" \
  --commission-rate "0.05" \
  --min-self-delegation "1" \
  --pubkey $(teritorid tendermint show-validator) \
  --moniker $NODENAME \
  --chain-id $CHAIN_ID \
  --gas 300000 \
  -y

**Comment by StakeTake** [comment]
fixed. thank you :)
