### ISSUE TITLE
--commission-max-change-rate.info: key not found

### ISSUE THREAD

**Issue by sukrosono** [StakeTake/guidecosmos#101]
I mess up the node name and the walletname. then I face --commission-max-change-rate.info: key not found.
If you can point me, please do so.

**Comment by StakeTake** [comment]
Try deleting the node and restarting the installation with the correct values.

**Comment by sukrosono** [comment]
it redownloading the go, etc. I still need help to get the correct values.
currently, it still unable to sync.
```
Error reconnecting to peer. Trying again addr={"id":"2371b28f366a61637ac76c2577264f79f0965447","ip":"176.9.19.162","port":26656} err="auth failure: secret conn failed: read tcp 192.168.0.108:34756->176.9.19.162:26656: i/o timeout" module=p2p tries=4
2:20PM INF Error reconnecting to peer. Trying again addr={"id":"0b42fd287d3bb0a20230e30d54b4b8facc412c53","ip":"176.9.149.15","port":26656} err="auth failure: secret conn failed: read tcp 192.168.0.108:53950->176.9.149.15:26656: i/o timeout" module=p2p tries=17

```

**Comment by StakeTake** [comment]
what node u installed? I try update peers\addrbook

**Comment by sukrosono** [comment]
I am not sure, I just run it once with messy value.
I can reconfigure the value directly in `.bash_profile` right?

this is my node:
```
{
  "protocol_version": {
    "p2p": "8",
    "block": "11",
    "app": "0"
  },
  "id": "b87153569cfcecd74c9bf6db46391c4a7378bb46",
  "listen_addr": "tcp://0.0.0.0:26656",
  "network": "teritori-testnet-v2",
  "version": "",
  "channels": "40202122233038606100",
  "moniker": "adi-80e1",
  "other": {
    "tx_index": "on",
    "rpc_address": "tcp://127.0.0.1:26657"
  }
}
```

**Comment by StakeTake** [comment]
sure, u can, I update addrbook now for teritori

**Comment by sukrosono** [comment]
I did [this](https://github.com/StakeTake/guidecosmos/tree/main/teritori/teritori-testnet-v2#start-with-state-sync) . but still unable to sync.

I still need guide / example on putting an important value on setup. Also thanks for your update.
atm:
```
"latest_block_hash": "",
  "latest_app_hash": "",
  "latest_block_height": "0",
  "latest_block_time": "1970-01-01T00:00:00Z",
  "earliest_block_hash": "",
  "earliest_app_hash": "",
  "earliest_block_height": "0",
  "earliest_block_time": "1970-01-01T00:00:00Z",
  "catching_up": true

```
also INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
